### ISSUE TITLE
Continental API - Stock struckture is wrong

### ISSUE THREAD

**Issue by martinvandijken** [ContinentalClothing/continentalclothing.com#2]
When opening the Stock result of the Continental API. 
The stock, size  and URL have the wrong values.

**Comment by nkhine** [comment]
@martinvandijken 
thanks for pointing this out, we have fixed this now.

**Comment by martinvandijken** [comment]
Is there a specific time, before this solved problem is visible in the result?
I can not see any changes in the result.

**Comment by nkhine** [comment]
please try, again i get

https://www.continentalclothing.com/api/v2/stock?api_key=`YOURAPIKEY`

```
[
  {
    "sku": "EP01-BB0",
    "name": "MEN’S / UNISEX CLASSIC JERSEY T-SHIRT",
    "colour": "Bright Blue",
    "size": "XS",
    "stock": 46,
    "inProduction": "80 due on 10-03-2016, 80 no date"
  },
  {
    "sku": "EP01-BB1",
    "name": "MEN’S / UNISEX CLASSIC JERSEY T-SHIRT",
    "colour": "Bright Blue",
    "size": "S",
    "stock": 528,
    "inProduction": "240 due on 10-03-2016, 240 no date"
  },
  {
```

**Comment by martinvandijken** [comment]
Thank You, Norman
It's working

**Comment by nkhine** [comment]
You are welcomed, out of interest, what is the website you are using the API from

**Comment by martinvandijken** [comment]
What do you mean?
I'am working for Continental Clothing Benelux, the dutch version.
And I am trying to translate the API code to our Dutch website continentalclothing.nl
I'am using this link also. https://www.continentalclothing.com/api/v2/

**Comment by nkhine** [comment]
i didn't know, you're still using the python's TurboGear 0.96 version

On 22 February 2016 at 11:46, martinvandijken notifications@github.com
wrote:

> What do you mean?
> I'am working for Continental Clothing Benelux, the dutch version.
> And I am trying to translate the API code to our Dutch website
> continentalclothing.nl
> I'am using this link also. https://www.continentalclothing.com/api/v2/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ContinentalClothing/continentalclothing.com/issues/2#issuecomment-187138357
> .

## 

%>>> "".join( [ {'_':'@','^':'.'}.get(c,None) or chr(97+(ord(c)-83)%26) for
c in ",adym,_)&uzq^zqf" ] )

**Comment by martinvandijken** [comment]
I don't know, the website we ar now using is a copy of the last .com version translated to Dutch.
I am trying to make the new website working with HTML5 and php with a bit Java.
This is the first time I'am using Json code to visualise data in to a website.
I am a rooky with this.

**Comment by nkhine** [comment]
OK, so your task is to migrate existing code into some sort of PHP/MySQL
shop?

On 22 February 2016 at 12:10, martinvandijken notifications@github.com
wrote:

> I don't know, the website we ar now using is a copy of the last .com
> version translated to Dutch.
> I am trying to make the new website working with HTML5 and php with a bit
> Java.
> This is the first time I'am using Json code to visualise data in to a
> website.
> I am a rooky with this.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ContinentalClothing/continentalclothing.com/issues/2#issuecomment-187146837
> .

## 

%>>> "".join( [ {'_':'@','^':'.'}.get(c,None) or chr(97+(ord(c)-83)%26) for
c in ",adym,_)&uzq^zqf" ] )

**Comment by martinvandijken** [comment]
It's not gonna be a shop just info. Like the continentalclothing.com without the order functions. But styled for the Dutch consumers. No Mysql. I am almost ready. Just the styling of the stock info and the securty measures to protect the stock info.

**Comment by nkhine** [comment]
it will be interesting to see, do you have a demo link?

On 22 February 2016 at 12:47, martinvandijken notifications@github.com
wrote:

> It's not gonna be a shop just info. Like the continentalclothing.com
> without the order functions. But styled for the Dutch consumers. No Mysql.
> I am almost ready. Just the styling of the stock info and the securty
> measures to protect the stock info.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ContinentalClothing/continentalclothing.com/issues/2#issuecomment-187156943
> .

## 

%>>> "".join( [ {'_':'@','^':'.'}.get(c,None) or chr(97+(ord(c)-83)%26) for
c in ",adym,_)&uzq^zqf" ] )

**Comment by martinvandijken** [comment]
No, not yet, Demo is running on My WAMP server localy.

**Comment by martinvandijken** [comment]
Hi Norman,
The website is online, www,continentalclothing.nl
Completely made with the Continental Clothing Api.
Made with PHP with Curl en Json.

**Comment by nkhine** [comment]
that is nice, are you caching the style results?

On 9 March 2016 at 09:29, martinvandijken notifications@github.com wrote:

> Hi Norman,
> The website is online, www,continentalclothing.nl
> Completely made with the Continental Clothing Api.
> Made with PHP with Curl en Json.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ContinentalClothing/continentalclothing.com/issues/2#issuecomment-194205399
> .

## 

%>>> "".join( [ {'_':'@','^':'.'}.get(c,None) or chr(97+(ord(c)-83)%26) for
c in ",adym,_)&uzq^zqf" ] )

**Comment by martinvandijken** [comment]
Yes, All of it. The styles, colours, fabric, afilliate, stock even the ICON fonts.
And with an extra the stock of Germany. This is presenten in XML by Germany.
All data from the Conti API. Stock results are visible with a customer login.
No order posibility.

**Comment by nkhine** [comment]
i am currently working on the API to post orders, it is 80% there, just
couple of issues that will need to be ironed out. you can see it at
https://www.continentalclothing.com/apidoc

On 9 March 2016 at 10:01, martinvandijken notifications@github.com wrote:

> Yes, All of it. The styles, colours, fabric, afilliate, stock even the
> ICON fonts.
> And with an extra the stock of Germany. This is presenten in XML by
> Germany.
> All data from the Conti API. Stock results are visible with a customer
> login.
> No order posibility.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ContinentalClothing/continentalclothing.com/issues/2#issuecomment-194218291
> .

## 

%>>> "".join( [ {'_':'@','^':'.'}.get(c,None) or chr(97+(ord(c)-83)%26) for
c in ",adym,_)&uzq^zqf" ] )

**Comment by martinvandijken** [comment]
There could be a posibility we are gonna use the order system in the future.
But As for now all our orders are made thru Email or the old fashion telephone.
